### ISSUE TITLE
Promise API

### ISSUE THREAD

**Issue by IcanDivideBy0** [remixz/messenger-bot#52]
Hi,
Thanks for your work!
It would be great to have a promise API in this lib, allowing for async/await compatibility. Would you accept such a PR ?

**Comment by IcanDivideBy0** [comment]
Looks like you heavily rely on `request` which have a promise based equivalent [`request-promise`](https://github.com/request/request-promise)

**Comment by remixz** [comment]
Yup, I'll happily take a look at a PR for this! It'd be nice if it could be done in a non-breaking way. You could do that by having any function return a Promise if the user doesn't pass a callback function.

I don't think you'd need to refactor the use of request to request-promise, since that isn't exposed to the user. As well, I want to keep the library with Node 4+ without a compilation step, so I'd rather not use async/await in the library itself. However, exposing Promises on the functions that take callbacks right now so someone can use them with async/await if they want to is 👍

**Comment by IcanDivideBy0** [comment]
Good!

I still think request promise could be usefull, the functions never returns anything, so they could always return a promise (which will be used or not). It could be as simple as
```js
myMethod (cb) {
  return requestPromise({
    ...
  })
  .then(res => {
    if (res.error) return Promise.reject(res.error)
    if (!cb) return res
    cb(null, res)
  })
  .catch(err => {
    if (!cb) return Promise.reject(err)
    cb(err)
  })
}
```
Is that ok for you ?

**Comment by ranyefet** [comment]
I would also suggest replacing `request` (or `request-promise`) with `node-fetch`
https://github.com/bitinn/node-fetch

**Comment by IcanDivideBy0** [comment]
I'm ok with that, I'll just wait an input from maintainers before refactoring PR

**Comment by youssef06** [comment]
Hi,
Is this in progress?
if not i can make a PR for it!

**Comment by IcanDivideBy0** [comment]
@youssef06 there already is a PR on this https://github.com/remixz/messenger-bot/pull/54. We're waiting for @remixz to review it.
